### ISSUE TITLE
Invalid Inspection of default value

### ISSUE THREAD

**Issue by revilwang** [zalando/intellij-swagger#235]
### IDE 

PyCharm 2018.3.4 (Professional Edition)
Build #PY-183.5429.31, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

### intellij-swagger plugin

v1.0.24

## Issue

Incorrect error inspection on default value

### How to produce

```yaml
openapi: '3.0.0'
paths:
  /testurl:
    get:
      security: []
      summary: brief summary
      description: detailed description
      parameters:
        - name: limit
          in: query
          description: record limit
          required: false
          example: 10
          schema:
            type: integer
            # The error message says: Validates to more than one variant
            default: 10   # <---- this is where the inspection error comes out
            minimum: 1
            maximum: 30
      responses:
        200:
          description: 成功查询
          content:
            application/json:
              schema:
                $ref: 'definitions/someDefinition.yaml'
              example:
                $ref: 'examples/someExample.json'
```

### Screenshot:

![image](https://user-images.githubusercontent.com/8424970/53063437-111e1600-34ff-11e9-9757-5196b30d7258.png)

According to the Spec, I don't think there are any issues on the definition of `limit` parameter, and I don't understand what the error message means.

**Comment by semonte** [comment]
Thank you for reporting the issue and apologies for the delayed response.

The issue is related to the JSON Schema validator provided by JetBrains, similar to https://github.com/zalando/intellij-swagger/issues/233. Version 2019.1 (https://www.jetbrains.com/idea/nextversion/) will fix this. 

If this is too much of an annoyance, you can disable the inspection from `Preferences -> Editor -> Inspections -> Swagger/OpenAPI Inspections`.

**Comment by revilwang** [comment]
Very much appreciated for the response. I will close this issue
